apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: vuejs-nodejs-example
build:
  artifacts:
  - image: vue-nodejs 
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deployment.yaml
    - service.yaml
